general:
  seed: 1
  wandb_disabled: "false"
  wandb_run_id: 
  freeze_encoder: False
  load_encoder: False
  load_decoder: False
  resume_training: False
  resume_ckpt_path: ""


trainer:
  max_epochs: 6000
  check_val_every_n_epoch: 5
  devices: 1


data:
  ignore_phenotype_tabular: True
  cmr_path_pickle_name: "cmr_paths.pkl"
  sax_slice_num: 6 # 6 for 3D, 1 for 2D
  image_size: [128, 128]
  t_downsampling_ratio: 1
  frame_to_keep: 25
  train_num_per_epoch: 1000
  num_train: 42000
  num_val: 1000
  num_test: 2000
  num_workers: 32
  batch_size: 2
  dataset_cls: Cardiac3DplusTAllAX


module:
  task_idx: 0 # reconstrucion: 0, regression: 1, segmentation: 2
  module_idx: 0 # ReconMAE: 0
  
  recon_hparams:
    enc_embed_dim: 1025
    enc_depth: 6
    enc_num_heads: 5
    dec_embed_dim: 1025
    dec_depth: 2
    dec_num_heads: 5

  training_hparams:
    patch_embed_cls: "PatchEmbed"
    patch_size: [5, 8, 8]
    pixel_unshuffle_scale: 1
    circular_pe: False
    use_enc_pe: True
    mask_loss: False
    shift_size: [0, 0 ,0]
    mask_type: "random"
    mask_ratio: 0.7
    loss_types: ["mse"]
    loss_weights: [1.0]
    train_log_rate: 2
    val_log_rate: 2
