general:
  seed: 1
  wandb_disabled: "false"
  wandb_run_id: 
  freeze_encoder: False
  resume_training: False
  load_encoder: True
  resume_ckpt_path: "checkpoints_imaging/downstream_seg_mae_allax.ckpt" # the ckpt for pretrained imaging model


data:
  ignore_phenotype_tabular: False
  cmr_path_pickle_name: "cmr_paths.pkl"
  sax_slice_num: 6 # 6 for 3D, 1 for 2D
  image_size: [128, 128]
  train_num_per_epoch: 1000
  num_train: 42000
  num_val: 1500
  num_test: 1000
  num_workers: 4
  batch_size: 1
  dataset_cls: Cardiac3DplusTAllAX
  load_seg: True


module:
  task_idx: 2 # reconstrucion: 0, regression: 1, segmentation: 2
  module_idx: 0 # SegMAE: 0
  
  seg_hparams:
    enc_embed_dim: 1025
    enc_depth: 6
    enc_num_heads: 5
    feature_size: 16
    dec_embed_dim: 1152
    spatial_dims: 3
    upsample_kernel_sizes: [[1, 2, 2], [1, 2, 2], [5, 2, 2]]

  training_hparams:
    lr: 0.0005
    patch_size: [5, 8, 8]
    circular_pe: False
    use_enc_pe: True
    shift_size: [0, 0 ,0]
    loss_types: ["dice"] # [mse]
    loss_weights: [1.0]
    train_log_rate: 2
    val_log_rate: 2
    grad_checkpointing: True
    test_scores_path: "all_dice.npy"


trainer:
  max_epochs: 500
  check_val_every_n_epoch: 5
